THEOS_PACKAGE_DIR_NAME = debs
TARGET = :clang
ARCHS = armv7 armv7s arm64

include theos/makefiles/common.mk

TWEAK_NAME = DarkClock
DarkClock_FILES = DarkClock.xm
DarkClock_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk